using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum InputAction
{
	Null,
	Click,
	DoubleClick,
    DoubleClickOnButton,
	SwipeUp,
	SwipeDown,
	SwipeLeft,
	SwipeRight,
    SwipeDiagUL,
    SwipeDiagUR,
    SwipeDiagDL,
    SwipeDiagDR,
	DragLeft,
	DragRight,
	DragUp,
	DragDown,
	Pressed,
	DoubleFingerTap,
	DoubleFingerDoubleTap,
	DoubleFingerSwipeLeft,
	DoubleFingerSwipeRight,
	DoubleFingerSwipeUp,
	DoubleFingerSwipeDown,
	DoubleFingerPressed,
	DoubleFingerDragDown,
	DoubleFingerDragUp,
	DoubleFingerDragLeft,
	DoubleFingerDragRight,
	TrippleFingerTap,
	TrippleFingerDoubleTap,
	TrippleFingerSwipeLeft,
	TrippleFingerSwipeRight,
	TrippleFingerSwipeUp,
	TrippleFingerSwipeDown,
	TrippleFingerPressed,
	TrippleFingerDragDown,
	TrippleFingerDragUp,
	TrippleFingerDragLeft,
	TrippleFingerDragRight,
	FourFingerTap,
	FourFingerDoubleTap,
	FourFingerSwipeLeft,
	FourFingerSwipeRight,
	FourFingerSwipeUp,
	FourFingerSwipeDown,
	FourFingerPressed,
	FourFingerDragDown,
	FourFingerDragUp,
	FourFingerDragLeft,
	FourFingerDragRight,
	FiveFingerTap,
	FiveFingerDoubleTap,
	FiveFingerSwipeLeft,
	FiveFingerSwipeRight,
	FiveFingerSwipeUp,
	FiveFingerSwipeDown,
	FiveFingerDragLeft,
	FiveFingerDragRight,
	FiveFingerDragUp,
	FiveFingerDragDown,
	FiveFingerPressed,
	PinchIn,
	PinchOut,

}

